; Script generated by Antigravity for 3F (Futuro Forbes)
; Este script crea un instalador profesional tipo Wizard para Windows.

[Setup]
; Información básica del app
AppId={{3F-FUTURO-FORBES-2026}}
AppName=3F Futuro Forbes
AppVersion=1.0.0
AppPublisher=Antigravity / Futuro Forbes
DefaultDirName={autopf}\3F_FuturoForbes
DefaultGroupName=3F Futuro Forbes
AllowNoIcons=yes
; Logo e imágenes (puedes personalizarlas)
; SetupIconFile=icon.ico
OutputDir=..\dist
OutputBaseFilename=3F_FuturoForbes_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copiar todos los archivos del proyecto (excluyendo lo innecesario)
Source: "..\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: ".venv, venv, .pytest_cache, __pycache__, .git, dist, backups, logs\*.log, *.db-journal, *.db-shm, *.db-wal"
; Nota: No incluimos el .db si queremos que el instalador no borre datos previos, 
; o lo incluimos como 'onlyifdoesntexist'
Source: "..\3f_app.db"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist

[Icons]
Name: "{group}\3F Futuro Forbes"; Filename: "{app}\3F_Launcher.vbs"; IconFilename: "{app}\frontend\static\js\favicon.ico"
Name: "{group}\{cm:UninstallProgram,3F Futuro Forbes}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\3F Futuro Forbes"; Filename: "{app}\3F_Launcher.vbs"; Tasks: desktopicon; IconFilename: "{app}\frontend\static\js\favicon.ico"

[Run]
; Ejecutar el script de configuración después de copiar los archivos
Filename: "{app}\installer\SETUP_WIZARD.bat"; Description: "Configurar entorno Python y Base de Datos (Recomendado)"; Flags: postinstall waituntilterminated

[UninstallRun]
; Limpieza opcional al desinstalar
; Filename: "{app}\scripts\cleanup.bat"; Flags: runhidden

[Code]
function InitializeSetup(): Boolean;
var
  PythonVersion: String;
  ErrorCode: Integer;
begin
  Result := True;
  // Opcional: Verificar si Python está instalado
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Software\Python\PythonCore\3.13\InstallPath', '', PythonVersion) then
  begin
    if not RegQueryStringValue(HKEY_LOCAL_MACHINE, 'Software\Python\PythonCore\3.13\InstallPath', '', PythonVersion) then
    begin
       if MsgBox('3F requiere Python 3.10 o superior. ' + #13#10 + '¿Deseas descargar Python ahora?', mbConfirmation, MB_YESNO) = IDYES then
       begin
         ShellExec('open', 'https://www.python.org/downloads/', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
       end;
    end;
  end;
end;
